{
  "name": "Import  Adventure Works",
  "compatibilityLevel": 1567,
  "model": {
    "culture": "en-US",
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "FactInternetSales",
        "lineageTag": "c2107eef-6407-447d-9f39-c6b7700ab3a1",
        "columns": [
          {
            "name": "ProductKey",
            "dataType": "int64",
            "sourceColumn": "ProductKey",
            "formatString": "0",
            "lineageTag": "22bc7392-6764-4d40-9178-e6e8f80a7667",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "OrderDateKey",
            "dataType": "int64",
            "sourceColumn": "OrderDateKey",
            "formatString": "0",
            "lineageTag": "251c8a1f-34d5-4977-af3b-73a78693fff5",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "name": "DueDateKey",
            "dataType": "int64",
            "sourceColumn": "DueDateKey",
            "formatString": "0",
            "lineageTag": "71cafbbb-d73d-40df-b98d-c4ba19efae55",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ShipDateKey",
            "dataType": "int64",
            "sourceColumn": "ShipDateKey",
            "formatString": "0",
            "lineageTag": "90ada8b2-dae3-438c-b0d3-c8690d29f0d5",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "name": "CustomerKey",
            "dataType": "int64",
            "sourceColumn": "CustomerKey",
            "formatString": "0",
            "lineageTag": "a312cc08-d5b7-43c7-a5e1-e259e29d8886",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "PromotionKey",
            "dataType": "int64",
            "sourceColumn": "PromotionKey",
            "formatString": "0",
            "lineageTag": "01803d66-4873-4894-9c6f-1ad8079dfdd5",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "name": "SalesTerritoryKey",
            "dataType": "int64",
            "sourceColumn": "SalesTerritoryKey",
            "formatString": "0",
            "lineageTag": "47c2ae4d-ca77-4492-ad94-d78bb39c6934",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "SalesOrderNumber",
            "dataType": "string",
            "sourceColumn": "SalesOrderNumber",
            "lineageTag": "ccb3649d-5c3f-4dc7-ab05-5ac60519ce6f",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "SalesOrderLineNumber",
            "dataType": "int64",
            "sourceColumn": "SalesOrderLineNumber",
            "formatString": "0",
            "lineageTag": "209c2e26-d735-44fc-a666-9d80f8157e63",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "name": "RevisionNumber",
            "dataType": "int64",
            "sourceColumn": "RevisionNumber",
            "formatString": "0",
            "lineageTag": "14d6ad3c-3979-4d62-aa3e-838155161264",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "name": "OrderQuantity",
            "dataType": "int64",
            "sourceColumn": "OrderQuantity",
            "formatString": "0",
            "lineageTag": "e0b795f7-4f5b-4e26-8c0e-dda9cc509ef7",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "name": "UnitPrice",
            "dataType": "decimal",
            "sourceColumn": "UnitPrice",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "455ab687-02d6-4a98-bdac-2338046014d7",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "ExtendedAmount",
            "dataType": "decimal",
            "sourceColumn": "ExtendedAmount",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "7a863e50-27ee-4640-b8a3-baa84cf62b31",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "UnitPriceDiscountPct",
            "dataType": "double",
            "sourceColumn": "UnitPriceDiscountPct",
            "lineageTag": "838e1ac9-53fb-42ae-a656-b36ace7bf90a",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "DiscountAmount",
            "dataType": "double",
            "sourceColumn": "DiscountAmount",
            "lineageTag": "347065df-ad3a-4ede-b26b-15294fcfde0a",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "ProductStandardCost",
            "dataType": "decimal",
            "sourceColumn": "ProductStandardCost",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "c04fbdd9-d6d5-43e6-a3ce-eb665f1ce262",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "TotalProductCost",
            "dataType": "decimal",
            "sourceColumn": "TotalProductCost",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "310cc317-aa9e-43a6-af0a-c67905226368",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "SalesAmount",
            "dataType": "decimal",
            "sourceColumn": "SalesAmount",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "37a92504-330e-4d99-80c7-3d0fefb2c629",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "TaxAmt",
            "dataType": "decimal",
            "sourceColumn": "TaxAmt",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "c2ec60e3-37c4-4e3a-ac82-7002ba180376",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "Freight",
            "dataType": "decimal",
            "sourceColumn": "Freight",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "7d5c7dab-ac52-49d5-98d8-7b9545447410",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "CarrierTrackingNumber",
            "dataType": "string",
            "sourceColumn": "CarrierTrackingNumber",
            "lineageTag": "676c24a9-b71b-4f49-8ee2-21ac0893fdaa",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "CustomerPONumber",
            "dataType": "string",
            "sourceColumn": "CustomerPONumber",
            "lineageTag": "fa194ecb-bee5-4c9f-9173-1bdf300ea438",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "OrderDate",
            "dataType": "dateTime",
            "sourceColumn": "OrderDate",
            "formatString": "General Date",
            "lineageTag": "16be0251-181b-4c3b-9a1c-215eadbce34a",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "DueDate",
            "dataType": "dateTime",
            "sourceColumn": "DueDate",
            "formatString": "General Date",
            "lineageTag": "fb02e0d0-1a89-446e-bc3d-b58642fc3303",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ShipDate",
            "dataType": "dateTime",
            "sourceColumn": "ShipDate",
            "formatString": "General Date",
            "lineageTag": "66e32f3b-5e07-47bc-8771-3fa469f7b159",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "CurrencyKey",
            "dataType": "int64",
            "sourceColumn": "CurrencyKey",
            "formatString": "0",
            "lineageTag": "bc6387b1-ff11-4f5b-bee9-5d9577ac4c6f",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "FactInternetSales-ec798b9c-b4ec-4b4c-9cad-060d285b3c5e",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Databases(\"localhost\"),",
                "    AdventureWorksDW2016_EXT = Source{[Name=\"AdventureWorksDW2016_EXT\"]}[Data],",
                "    dbo_FactInternetSales = AdventureWorksDW2016_EXT{[Schema=\"dbo\",Item=\"FactInternetSales\"]}[Data]",
                "in",
                "    dbo_FactInternetSales"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Sales",
            "expression": "SUM( FactInternetSales[SalesAmount])",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "9a8d6431-5dcc-4aa6-bb8e-a0d797ebed52",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ]
      },
      {
        "name": "DimCurrency",
        "lineageTag": "277a72ca-6021-48d4-a7c4-637fa5c5115a",
        "columns": [
          {
            "name": "CurrencyKey",
            "dataType": "int64",
            "sourceColumn": "CurrencyKey",
            "formatString": "0",
            "lineageTag": "4cbd9021-2022-4384-ad63-a9207731e697",
            "summarizeBy": "count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "CurrencyAlternateKey",
            "dataType": "string",
            "sourceColumn": "CurrencyAlternateKey",
            "lineageTag": "39ffe630-4376-4ffb-8221-94d6e8fc37f3",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "CurrencyName",
            "dataType": "string",
            "sourceColumn": "CurrencyName",
            "lineageTag": "77a4e9b5-7123-4350-a12c-3ad184c95060",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "DimCurrency-cf532785-42a6-4b07-a9cb-be93be05e9df",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Databases(\"localhost\"),",
                "    AdventureWorksDW2016_EXT = Source{[Name=\"AdventureWorksDW2016_EXT\"]}[Data],",
                "    dbo_DimCurrency = AdventureWorksDW2016_EXT{[Schema=\"dbo\",Item=\"DimCurrency\"]}[Data]",
                "in",
                "    dbo_DimCurrency"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "DimCustomer",
        "lineageTag": "d5c8de10-618a-4bca-9b80-382be70dc67f",
        "columns": [
          {
            "name": "CustomerKey",
            "dataType": "int64",
            "sourceColumn": "CustomerKey",
            "formatString": "0",
            "lineageTag": "ae2054d8-7f1c-4502-8802-eebab2d810a2",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "GeographyKey",
            "dataType": "int64",
            "sourceColumn": "GeographyKey",
            "formatString": "0",
            "lineageTag": "919e8a1c-0bb8-40f8-ba97-c1e7f22dc653",
            "summarizeBy": "count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "CustomerAlternateKey",
            "dataType": "string",
            "sourceColumn": "CustomerAlternateKey",
            "lineageTag": "f9ac1c19-9eb1-4a63-80c4-34c9f7a5caab",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Title",
            "dataType": "string",
            "sourceColumn": "Title",
            "lineageTag": "67230b96-ad58-4d46-b9b3-b198e6796566",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "FirstName",
            "dataType": "string",
            "sourceColumn": "FirstName",
            "lineageTag": "f4f6e063-5225-4b50-933f-90f06048b489",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "MiddleName",
            "dataType": "string",
            "sourceColumn": "MiddleName",
            "lineageTag": "c1025172-f793-4bd9-8500-15fefea29035",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "LastName",
            "dataType": "string",
            "sourceColumn": "LastName",
            "lineageTag": "e2d163d1-e876-47a7-b71c-0d8cbf17ad79",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "NameStyle",
            "dataType": "boolean",
            "sourceColumn": "NameStyle",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "1d26d25f-28e8-4458-abbe-cadebab67d33",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "BirthDate",
            "dataType": "dateTime",
            "sourceColumn": "BirthDate",
            "formatString": "Long Date",
            "lineageTag": "fc1caeb3-50a3-40f2-bb08-be7b81cce7a9",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "MaritalStatus",
            "dataType": "string",
            "sourceColumn": "MaritalStatus",
            "lineageTag": "ac078c13-69b8-4ad0-9b36-e25bc8c40bd4",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Suffix",
            "dataType": "string",
            "sourceColumn": "Suffix",
            "lineageTag": "616d5042-e227-46c5-aafa-b39010f30fe8",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Gender",
            "dataType": "string",
            "sourceColumn": "Gender",
            "lineageTag": "30fdc93c-f598-4d33-885c-5d64079a9854",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "EmailAddress",
            "dataType": "string",
            "sourceColumn": "EmailAddress",
            "lineageTag": "274dc237-4c62-4755-ac28-4f2fbeaf3388",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "YearlyIncome",
            "dataType": "decimal",
            "sourceColumn": "YearlyIncome",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "f962692f-a377-4b3b-8ece-38e8362b30ab",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "TotalChildren",
            "dataType": "int64",
            "sourceColumn": "TotalChildren",
            "formatString": "0",
            "lineageTag": "c1a8342a-b185-403a-b94f-ab9f83df02d2",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "NumberChildrenAtHome",
            "dataType": "int64",
            "sourceColumn": "NumberChildrenAtHome",
            "formatString": "0",
            "lineageTag": "2592766a-2c29-415b-9975-b02ae7d88ba5",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "EnglishEducation",
            "dataType": "string",
            "sourceColumn": "EnglishEducation",
            "lineageTag": "ec686aa8-860d-4221-934f-b93318e9919f",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "SpanishEducation",
            "dataType": "string",
            "sourceColumn": "SpanishEducation",
            "lineageTag": "1935bc92-5ffe-4a5b-9474-2c56d7710fd9",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "FrenchEducation",
            "dataType": "string",
            "sourceColumn": "FrenchEducation",
            "lineageTag": "3ccd6903-5cec-43ad-81c7-aba03d4c342f",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "EnglishOccupation",
            "dataType": "string",
            "sourceColumn": "EnglishOccupation",
            "lineageTag": "4eada2d9-698d-407b-bc1f-d3fe541f3fc2",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "SpanishOccupation",
            "dataType": "string",
            "sourceColumn": "SpanishOccupation",
            "lineageTag": "f14ec3f0-d29c-4c79-bdc9-f072520ac843",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "FrenchOccupation",
            "dataType": "string",
            "sourceColumn": "FrenchOccupation",
            "lineageTag": "c5b6c537-55e2-4a52-9642-9c6e5008d4d1",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "HouseOwnerFlag",
            "dataType": "string",
            "sourceColumn": "HouseOwnerFlag",
            "lineageTag": "c5da7929-61f5-4c54-b6bd-be63430994d7",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "NumberCarsOwned",
            "dataType": "int64",
            "sourceColumn": "NumberCarsOwned",
            "formatString": "0",
            "lineageTag": "96f2acc5-7209-43d5-a455-8d0dc9e6f881",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "AddressLine1",
            "dataType": "string",
            "sourceColumn": "AddressLine1",
            "lineageTag": "334f865b-00ca-4c61-9e30-4a28915d9d9f",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "AddressLine2",
            "dataType": "string",
            "sourceColumn": "AddressLine2",
            "lineageTag": "48614c34-4000-4c92-8de8-06b8139e3ce7",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Phone",
            "dataType": "string",
            "sourceColumn": "Phone",
            "lineageTag": "2e66d892-be47-46fa-b7da-af7ffa389576",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "DateFirstPurchase",
            "dataType": "dateTime",
            "sourceColumn": "DateFirstPurchase",
            "formatString": "Long Date",
            "lineageTag": "e8326114-d42b-4dd3-8206-95edd4a5076e",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "CommuteDistance",
            "dataType": "string",
            "sourceColumn": "CommuteDistance",
            "lineageTag": "02c89c8d-ce18-4470-bcd2-cb61b5321fca",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "DimCustomer-d68702f8-72c5-4ec3-84ba-64b904c9a0ee",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Databases(\"localhost\"),",
                "    AdventureWorksDW2016_EXT = Source{[Name=\"AdventureWorksDW2016_EXT\"]}[Data],",
                "    dbo_DimCustomer = AdventureWorksDW2016_EXT{[Schema=\"dbo\",Item=\"DimCustomer\"]}[Data]",
                "in",
                "    dbo_DimCustomer"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Date",
        "lineageTag": "cba70b79-5ebe-44d4-82f6-9e39bf595f55",
        "dataCategory": "Time",
        "columns": [
          {
            "name": "DateKey",
            "dataType": "int64",
            "sourceColumn": "DateKey",
            "formatString": "0",
            "lineageTag": "16b2c3ee-71dd-4a0e-bc6e-e1a9fd2a6df1",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "FullDateAlternateKey",
            "dataType": "dateTime",
            "isKey": true,
            "sourceColumn": "FullDateAlternateKey",
            "formatString": "Long Date",
            "lineageTag": "229458ea-4975-464e-b77b-458b0c1d31db",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "DayNumberOfWeek",
            "dataType": "int64",
            "sourceColumn": "DayNumberOfWeek",
            "formatString": "0",
            "lineageTag": "6cd2812d-16c4-4c80-8784-55b1ea1c360b",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "EnglishDayNameOfWeek",
            "dataType": "string",
            "sourceColumn": "EnglishDayNameOfWeek",
            "lineageTag": "3086bfc6-c611-4646-9143-de9ba1424514",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "SpanishDayNameOfWeek",
            "dataType": "string",
            "sourceColumn": "SpanishDayNameOfWeek",
            "lineageTag": "ba92bd52-d363-4ba0-aa65-c20ab4c5060c",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "FrenchDayNameOfWeek",
            "dataType": "string",
            "sourceColumn": "FrenchDayNameOfWeek",
            "lineageTag": "2461f81b-5a06-4851-bbea-0d1694b89521",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "DayNumberOfMonth",
            "dataType": "int64",
            "sourceColumn": "DayNumberOfMonth",
            "formatString": "0",
            "lineageTag": "09f018d1-7ded-4225-a504-9788c0c904c3",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "DayNumberOfYear",
            "dataType": "int64",
            "sourceColumn": "DayNumberOfYear",
            "formatString": "0",
            "lineageTag": "58d0268d-2050-4ec3-acf8-f75c5b613559",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "WeekNumberOfYear",
            "dataType": "int64",
            "sourceColumn": "WeekNumberOfYear",
            "formatString": "0",
            "lineageTag": "fb9fa15e-1764-4305-8668-8d441b7d1e79",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "EnglishMonthName",
            "dataType": "string",
            "sourceColumn": "EnglishMonthName",
            "lineageTag": "a63e941c-5a86-40ec-8262-348826f52a18",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "SpanishMonthName",
            "dataType": "string",
            "sourceColumn": "SpanishMonthName",
            "lineageTag": "36cb267c-efc4-4140-8c32-3fe4f675db47",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "FrenchMonthName",
            "dataType": "string",
            "sourceColumn": "FrenchMonthName",
            "lineageTag": "1bf2dcc3-3591-4f8c-b5de-cc335a5cbfc9",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "MonthNumberOfYear",
            "dataType": "int64",
            "sourceColumn": "MonthNumberOfYear",
            "formatString": "0",
            "lineageTag": "aa6199ce-a658-414d-849e-1e52b7643999",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "CalendarQuarter",
            "dataType": "int64",
            "sourceColumn": "CalendarQuarter",
            "formatString": "0",
            "lineageTag": "925df013-9825-42db-aa28-ba079c570321",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "CalendarYear",
            "dataType": "int64",
            "sourceColumn": "CalendarYear",
            "formatString": "0",
            "lineageTag": "6dca5404-6695-44f1-83f8-31733139f1ab",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "CalendarSemester",
            "dataType": "int64",
            "sourceColumn": "CalendarSemester",
            "formatString": "0",
            "lineageTag": "3d30009b-b5a7-40d0-84c8-bf9570888b5d",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "FiscalQuarter",
            "dataType": "int64",
            "sourceColumn": "FiscalQuarter",
            "formatString": "0",
            "lineageTag": "6d15711a-5dba-4d8a-b912-21468e0993dd",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "FiscalYear",
            "dataType": "int64",
            "sourceColumn": "FiscalYear",
            "formatString": "0",
            "lineageTag": "a037d287-5964-4622-aa24-5a42dff2a55b",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "FiscalSemester",
            "dataType": "int64",
            "sourceColumn": "FiscalSemester",
            "formatString": "0",
            "lineageTag": "f843a1c5-8452-4ae2-8858-adbf02693248",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Date-6f3184ff-b2e8-44af-923e-d211d9f84e39",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Databases(\"localhost\"),",
                "    AdventureWorksDW2016_EXT = Source{[Name=\"AdventureWorksDW2016_EXT\"]}[Data],",
                "    dbo_DimDate = AdventureWorksDW2016_EXT{[Schema=\"dbo\",Item=\"DimDate\"]}[Data]",
                "in",
                "    dbo_DimDate"
              ]
            }
          }
        ],
        "changedProperties": [
          {
            "property": "Name"
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "DimProduct",
        "lineageTag": "ef4788f7-24dd-4be2-ba7e-e11aff1dfc0f",
        "columns": [
          {
            "name": "ProductKey",
            "dataType": "int64",
            "sourceColumn": "ProductKey",
            "formatString": "0",
            "lineageTag": "39dc5fce-aaac-4821-881b-d00cb12fad03",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ProductAlternateKey",
            "dataType": "string",
            "sourceColumn": "ProductAlternateKey",
            "lineageTag": "61a11909-3091-48e1-adfb-b08201788b8d",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "WeightUnitMeasureCode",
            "dataType": "string",
            "sourceColumn": "WeightUnitMeasureCode",
            "lineageTag": "e23068ea-1eb7-4e3c-bd80-51d5cf63075e",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "SizeUnitMeasureCode",
            "dataType": "string",
            "sourceColumn": "SizeUnitMeasureCode",
            "lineageTag": "058568e0-50b0-4da2-bce8-a9a0a0deee11",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "EnglishProductName",
            "dataType": "string",
            "sourceColumn": "EnglishProductName",
            "lineageTag": "ada39642-1e65-45aa-8360-943c86519ba4",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "SpanishProductName",
            "dataType": "string",
            "sourceColumn": "SpanishProductName",
            "lineageTag": "985499fc-314a-4d70-86bf-de2e4996f555",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "FrenchProductName",
            "dataType": "string",
            "sourceColumn": "FrenchProductName",
            "lineageTag": "9cf335b7-ce63-4fa4-b727-10a9c1bba58b",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "StandardCost",
            "dataType": "decimal",
            "sourceColumn": "StandardCost",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "efcf8b70-aa37-4c27-96ab-722a881ee97b",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "FinishedGoodsFlag",
            "dataType": "boolean",
            "sourceColumn": "FinishedGoodsFlag",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "5c8d2c9f-4d5c-4d30-8fff-2ed87cacba52",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Color",
            "dataType": "string",
            "sourceColumn": "Color",
            "lineageTag": "592a3d87-1474-4fbc-bc06-6d8bfbecaa51",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "SafetyStockLevel",
            "dataType": "int64",
            "sourceColumn": "SafetyStockLevel",
            "formatString": "0",
            "lineageTag": "07f8eb99-d194-4bcc-afb3-e28e705b4da7",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ReorderPoint",
            "dataType": "int64",
            "sourceColumn": "ReorderPoint",
            "formatString": "0",
            "lineageTag": "c4537808-61ac-4e71-9fa7-96791048647c",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ListPrice",
            "dataType": "decimal",
            "sourceColumn": "ListPrice",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "7a7c5a06-b575-4dcb-8be3-be33a65d2d50",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "Size",
            "dataType": "string",
            "sourceColumn": "Size",
            "lineageTag": "763cdac5-e879-43dd-b985-a8da1b45fcbe",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "SizeRange",
            "dataType": "string",
            "sourceColumn": "SizeRange",
            "lineageTag": "0877aa6f-c9cb-44d9-a86e-e542417128f1",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Weight",
            "dataType": "double",
            "sourceColumn": "Weight",
            "lineageTag": "1361dadb-107d-46f6-9939-9f19d1b035d7",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "DaysToManufacture",
            "dataType": "int64",
            "sourceColumn": "DaysToManufacture",
            "formatString": "0",
            "lineageTag": "a8426ba7-8bc6-45ba-b077-bf71bde1ea45",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ProductLine",
            "dataType": "string",
            "sourceColumn": "ProductLine",
            "lineageTag": "5903d9a1-be6a-41be-8fd0-6cda6fbc7070",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "DealerPrice",
            "dataType": "decimal",
            "sourceColumn": "DealerPrice",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "467944f4-a390-4e6c-a672-e5f3ff5631ca",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "Class",
            "dataType": "string",
            "sourceColumn": "Class",
            "lineageTag": "bee52a38-d92d-4f40-81a7-d1ad1094b74a",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Style",
            "dataType": "string",
            "sourceColumn": "Style",
            "lineageTag": "268ebd72-c27a-4c6d-9eaa-ef17b887dc46",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ModelName",
            "dataType": "string",
            "sourceColumn": "ModelName",
            "lineageTag": "41a6c248-d77c-4690-8cda-36b9028fdbe0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "EnglishDescription",
            "dataType": "string",
            "sourceColumn": "EnglishDescription",
            "lineageTag": "682bc6af-e42d-4b86-8226-0505b7f4a763",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "FrenchDescription",
            "dataType": "string",
            "sourceColumn": "FrenchDescription",
            "lineageTag": "25e63a1d-03a1-4d18-861b-4464d5260b3b",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ChineseDescription",
            "dataType": "string",
            "sourceColumn": "ChineseDescription",
            "lineageTag": "e3b3d0f5-6f62-4442-9fe4-4c44c7af99c5",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ArabicDescription",
            "dataType": "string",
            "sourceColumn": "ArabicDescription",
            "lineageTag": "d11e7654-5988-431f-aa8b-1c53972f3461",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "HebrewDescription",
            "dataType": "string",
            "sourceColumn": "HebrewDescription",
            "lineageTag": "50880a3a-21c2-4a22-b720-07200a6c0bb1",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ThaiDescription",
            "dataType": "string",
            "sourceColumn": "ThaiDescription",
            "lineageTag": "d40927f7-7e4c-4f40-88cb-636eafbf57b0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "GermanDescription",
            "dataType": "string",
            "sourceColumn": "GermanDescription",
            "lineageTag": "161b4355-7c11-4e11-9cce-d9499a22a17b",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "JapaneseDescription",
            "dataType": "string",
            "sourceColumn": "JapaneseDescription",
            "lineageTag": "d8a1b042-3d95-40e1-bbea-7695ac028dbb",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "TurkishDescription",
            "dataType": "string",
            "sourceColumn": "TurkishDescription",
            "lineageTag": "7b87fe93-3e59-4a05-b3a6-8a91290fd1f1",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "StartDate",
            "dataType": "dateTime",
            "sourceColumn": "StartDate",
            "formatString": "General Date",
            "lineageTag": "a79c07e6-f035-498b-90cb-7d3c122732ce",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "EndDate",
            "dataType": "dateTime",
            "sourceColumn": "EndDate",
            "formatString": "General Date",
            "lineageTag": "1b09a6d5-1b87-47e4-951f-96d58507336f",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Status",
            "dataType": "string",
            "sourceColumn": "Status",
            "lineageTag": "ee4a88a8-8e1b-45b4-9b79-db0ca2553649",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "DimProduct-31a470f7-6ea6-47a7-be8e-e3f20b17c277",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Databases(\"localhost\"),",
                "    AdventureWorksDW2016_EXT = Source{[Name=\"AdventureWorksDW2016_EXT\"]}[Data],",
                "    dbo_DimProduct = AdventureWorksDW2016_EXT{[Schema=\"dbo\",Item=\"DimProduct\"]}[Data],",
                "    #\"Removed Columns\" = Table.RemoveColumns(dbo_DimProduct,{\"ProductSubcategoryKey\"})",
                "in",
                "    #\"Removed Columns\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ]
      },
      {
        "name": "DimSalesTerritory",
        "lineageTag": "c8874bfc-c236-46ea-96c8-d610ba8fd80e",
        "columns": [
          {
            "name": "SalesTerritoryKey",
            "dataType": "int64",
            "sourceColumn": "SalesTerritoryKey",
            "formatString": "0",
            "lineageTag": "98382b05-c1a3-47d6-be4d-eebedc97f4d1",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "SalesTerritoryAlternateKey",
            "dataType": "int64",
            "sourceColumn": "SalesTerritoryAlternateKey",
            "formatString": "0",
            "lineageTag": "d757c8f4-c1ec-4da2-9027-9fd35e839dee",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "SalesTerritoryRegion",
            "dataType": "string",
            "sourceColumn": "SalesTerritoryRegion",
            "lineageTag": "f09c3512-c5dd-4d1b-9e43-4c208d8bfefe",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "SalesTerritoryCountry",
            "dataType": "string",
            "sourceColumn": "SalesTerritoryCountry",
            "lineageTag": "586e5b8d-7a50-408f-9b1e-7e72a3341f04",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "SalesTerritoryGroup",
            "dataType": "string",
            "sourceColumn": "SalesTerritoryGroup",
            "lineageTag": "efce6900-43cc-44ca-a11b-d9d6bc7f1fcd",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "DimSalesTerritory-ace884a2-8e6d-4c58-b39d-68e588a568c8",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Databases(\"localhost\"),",
                "    AdventureWorksDW2016_EXT = Source{[Name=\"AdventureWorksDW2016_EXT\"]}[Data],",
                "    dbo_DimSalesTerritory = AdventureWorksDW2016_EXT{[Schema=\"dbo\",Item=\"DimSalesTerritory\"]}[Data],",
                "    #\"Removed Columns\" = Table.RemoveColumns(dbo_DimSalesTerritory,{\"SalesTerritoryImage\"})",
                "in",
                "    #\"Removed Columns\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ]
      },
      {
        "name": "FactInternetSalesReason",
        "lineageTag": "b1c96e2e-f9a9-4b87-9949-61ee26f33a88",
        "columns": [
          {
            "name": "SalesOrderNumber",
            "dataType": "string",
            "sourceColumn": "SalesOrderNumber",
            "lineageTag": "6a890eca-87c2-4c38-b8fd-4393bd21027d",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "SalesOrderLineNumber",
            "dataType": "int64",
            "sourceColumn": "SalesOrderLineNumber",
            "formatString": "0",
            "lineageTag": "12598256-e709-4448-a735-fe2365dc6543",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "SalesReasonKey",
            "dataType": "int64",
            "sourceColumn": "SalesReasonKey",
            "formatString": "0",
            "lineageTag": "20778828-af0a-4219-ab8c-cfdb3836cc7d",
            "summarizeBy": "count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "FactInternetSalesReason-d698d179-86ef-4fb0-9241-2babe94f7f59",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Databases(\"localhost\"),",
                "    AdventureWorksDW2016_EXT = Source{[Name=\"AdventureWorksDW2016_EXT\"]}[Data],",
                "    dbo_FactInternetSalesReason = AdventureWorksDW2016_EXT{[Schema=\"dbo\",Item=\"FactInternetSalesReason\"]}[Data]",
                "in",
                "    dbo_FactInternetSalesReason"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "88b5f9e8-f4e5-42c5-9b3b-75d54906754a",
        "fromTable": "FactInternetSales",
        "fromColumn": "CustomerKey",
        "toTable": "DimCustomer",
        "toColumn": "CustomerKey",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ]
      },
      {
        "name": "bfdacd57-0d8b-46da-a8ed-8f7ceb965620",
        "fromTable": "FactInternetSales",
        "fromColumn": "DueDateKey",
        "toTable": "Date",
        "toColumn": "DateKey",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ]
      },
      {
        "name": "30e49d3b-8bd5-46f5-8c72-6cb90e71f9b7",
        "fromTable": "FactInternetSales",
        "fromColumn": "OrderDateKey",
        "toTable": "Date",
        "toColumn": "DateKey",
        "isActive": false,
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ]
      },
      {
        "name": "46ae9d63-3cc9-4713-85c5-feeb132dd9b7",
        "fromTable": "FactInternetSales",
        "fromColumn": "ShipDateKey",
        "toTable": "Date",
        "toColumn": "DateKey",
        "isActive": false,
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ]
      },
      {
        "name": "8a8fffbe-86aa-4c52-9ac3-be7467c58e88",
        "fromTable": "FactInternetSales",
        "fromColumn": "ProductKey",
        "toTable": "DimProduct",
        "toColumn": "ProductKey",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ]
      },
      {
        "name": "99f717cc-c8f3-4c60-836e-9a29b8b2d04f",
        "fromTable": "FactInternetSales",
        "fromColumn": "SalesTerritoryKey",
        "toTable": "DimSalesTerritory",
        "toColumn": "SalesTerritoryKey",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ]
      }
    ],
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "Version": "1.0.0",
            "Language": "en-US",
            "DynamicImprovement": "HighConfidence"
          },
          "contentType": "json"
        }
      }
    ],
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"FactInternetSales\",\"DimCurrency\",\"DimCustomer\",\"Date\",\"DimProduct\",\"DimSalesTerritory\",\"FactInternetSalesReason\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.115.1006.0 (23.03)"
      },
      {
        "name": "TabularEditor_SerializeOptions",
        "value": "{\"IgnoreInferredObjects\":true,\"IgnoreInferredProperties\":true,\"IgnoreTimestamps\":true,\"SplitMultilineStrings\":true,\"PrefixFilenames\":false,\"LocalTranslations\":false,\"LocalPerspectives\":false,\"LocalRelationships\":false,\"Levels\":[\"Data Sources\",\"Shared Expressions\",\"Perspectives\",\"Relationships\",\"Roles\",\"Tables\",\"Tables/Columns\",\"Tables/Hierarchies\",\"Tables/Measures\",\"Tables/Partitions\",\"Tables/Calculation Items\",\"Translations\"]}"
      }
    ]
  }
}